apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "chaos-mesh.svc" . }}
  labels:
    {{- include "chaos-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
spec:
  type: {{ .Values.controllerManager.service.type }}
  ports:
  {{- if .Values.enableProfiling }}
    - port: 10081
      targetPort: pprof
      protocol: TCP
      name: pprof
  {{- end }}
    - port: 10080
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "chaos-mesh.selectors" . | indent 4 }}
    app.kubernetes.io/component: controller-manager
