{{ if not .Values.webhook.certManager.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: webhook-mw-job
  labels:
    app.kubernetes.io/name: {{ template "chaos-mesh.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: webhook-mw-job
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: webhook-mw-job
    {{- with .Values.postJobs.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Values.controllerManager.serviceAccount }}
      containers:
        - name: "{{ .Release.Name }}-job-mw"
          image: {{ .Values.kubectlImage }}
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - |
              set -e
              K8S_NAMESPACE={{ .Release.Namespace }}
              CA_BUNDLE=$(kubectl get configmap -n kube-system extension-apiserver-authentication -o=jsonpath='{.data.client-ca-file}' | base64 | tr -d '\n')

              if [ ! $CA_BUNDLE ]; then
                  echo "ERROR: CA_BUNDLE is empty!" >&2
                  exit 1
              fi

              cat <<EOF | kubectl -n ${K8S_NAMESPACE} apply -f -
              apiVersion: admissionregistration.k8s.io/v1beta1
              kind: MutatingWebhookConfiguration
              metadata:
                name: {{ template "chaos-mesh.mutation" . }}
              webhooks:
                - name: {{ template "chaos-mesh.webhook" . }}
                  clientConfig:
                    caBundle: "${CA_BUNDLE}"
                    service:
                      name: {{ template "chaos-mesh.svc" . }}
                      namespace: {{ .Release.Namespace }}
                      path: "/inject-v1-pod"
                {{- range $crd := .Values.webhook.CRDS }}
                - name: m{{ $crd }}.kb.io
                  clientConfig:
                    caBundle: "${CA_BUNDLE}"
                    service:
                      name: {{ template "chaos-mesh.svc" $ }}
                      namespace: {{ $.Release.Namespace }}
                      path: /mutate-pingcap-com-v1alpha1-{{ $crd }}
                {{- end }}
              ---
              apiVersion: admissionregistration.k8s.io/v1beta1
              kind: ValidatingWebhookConfiguration
              metadata:
                name: {{ template "chaos-mesh.validation" . }}
              webhooks:
                {{- range $crd := .Values.webhook.CRDS }}
                - name: v{{ $crd }}.kb.io
                  clientConfig:
                    caBundle: "${CA_BUNDLE}"
                    service:
                      name: {{ template "chaos-mesh.svc" $ }}
                      namespace: {{ $.Release.Namespace }}
                      path: /validate-pingcap-com-v1alpha1-{{ $crd }}
                {{- end }}
              EOF
{{- end }}
