ignoreGeneratedHeader = false
severity = "error"
confidence = 0.8
errorCode = 1
warningCode = 0

[rule.blank-imports]
[rule.context-as-argument]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.if-return]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.indent-error-flow]
[rule.empty-block]
[rule.superfluous-else]
[rule.modifies-parameter]

# Add these once issues are fixed
#[rule.var-naming]
#  severity = "warning"
#[rule.confusing-naming]
#  severity = "warning"
[rule.confusing-results]
  severity = "warning"
[rule.flag-parameter]
  severity = "warning"
#[rule.unused-parameter]
#  severity = "warning"

# Decide whether we want these rules
# [rule.exported]

# Already checked by megacheck
# [rule.unreachable-code]

# Adding these will slow down the linter
# They are already provided by megacheck
# [rule.unexported-return]
# [rule.time-naming]
# [rule.errorf]

# Adding these will slow down the linter
# Not sure if they are already provided by megacheck
# [rule.var-declaration]
# [rule.context-keys-type]
