
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-chaos-mesh-org-v1alpha1-dnschaos
  failurePolicy: Fail
  name: mdnschaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dnschaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-chaos-mesh-org-v1alpha1-awschaos
  failurePolicy: Fail
  name: mawschaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awschaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-chaos-mesh-org-v1alpha1-iochaos
  failurePolicy: Fail
  name: miochaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - iochaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-chaos-mesh-org-v1alpha1-jvmchaos
  failurePolicy: Fail
  name: mjvmchaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jvmchaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-chaos-mesh-org-v1alpha1-kernelchaos
  failurePolicy: Fail
  name: mkernelchaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kernelchaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-chaos-mesh-org-v1alpha1-networkchaos
  failurePolicy: Fail
  name: mnetworkchaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networkchaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-chaos-mesh-org-v1alpha1-podchaos
  failurePolicy: Fail
  name: mpodchaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podchaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-chaos-mesh-org-v1alpha1-podiochaos
  failurePolicy: Fail
  name: mpodiochaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podiochaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-chaos-mesh-org-v1alpha1-podnetworkchaos
  failurePolicy: Fail
  name: mpodnetworkchaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podnetworkchaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-chaos-mesh-org-v1alpha1-stresschaos
  failurePolicy: Fail
  name: mstresschaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stresschaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-chaos-mesh-org-v1alpha1-timechaos
  failurePolicy: Fail
  name: mtimechaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - timechaos

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-chaos-mesh-org-v1alpha1-dnschaos
  failurePolicy: Fail
  name: vdnschaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dnschaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-chaos-mesh-org-v1alpha1-awschaos
  failurePolicy: Fail
  name: vawschaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awschaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-chaos-mesh-org-v1alpha1-iochaos
  failurePolicy: Fail
  name: viochaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - iochaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-chaos-mesh-org-v1alpha1-jvmchaos
  failurePolicy: Fail
  name: vjvmchaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jvmchaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-chaos-mesh-org-v1alpha1-kernelchaos
  failurePolicy: Fail
  name: vkernelchaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kernelchaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-chaos-mesh-org-v1alpha1-networkchaos
  failurePolicy: Fail
  name: vnetworkchaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networkchaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-chaos-mesh-org-v1alpha1-podchaos
  failurePolicy: Fail
  name: vpodchaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podchaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-chaos-mesh-org-v1alpha1-podnetworkchaos
  failurePolicy: Fail
  name: vpodnetworkchaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podnetworkchaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-chaos-mesh-org-v1alpha1-stresschaos
  failurePolicy: Fail
  name: vstresschaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stresschaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-chaos-mesh-org-v1alpha1-timechaos
  failurePolicy: Fail
  name: vtimechaos.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - timechaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /inject-v1-pod
  failurePolicy: Fail
  name: vpod.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-auth
  failurePolicy: Fail
  name: vauth.kb.io
  rules:
  - apiGroups:
    - chaos-mesh.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - '*'
