blank_issues_enabled: true
contact_links:
- name: \U0001F914 Ask a question
  url: https://github.com/chaos-mesh/chaos-mesh/discussions/new?category=q-a
  about: Chaos Mesh not works as expected? Or not sure about how to use Chaos Mesh? Ask a question here!
