apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: chaos-collector
  labels:
    app.kubernetes.io/name: {{ template "chaos-operator.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: collector
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  replicas: {{ .Values.collector.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "chaos-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "chaos-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: collector
    spec:
    {{- if .Values.controllerManager.serviceAccount }}
      serviceAccount: {{ .Values.controllerManager.serviceAccount }}
    {{- end }}
      containers:
      - name: chaos-collector
        image: {{ .Values.collector.image }}
        imagePullPolicy: {{ .Values.collector.imagePullPolicy | default "IfNotPresent" }}
        resources:
{{ toYaml .Values.collector.resources | indent 12 }}
        command:
          - /usr/local/bin/chaos-collector
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TZ
            value: {{ .Values.timezone | default "UTC" }}
    {{- with .Values.controllerManager.nodeSelector }}
    nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.collector.affinity }}
    affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.collector.tolerations }}
    tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
