---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaosfs-cockroachdb
  namespace: chaos-testing
  labels:
    app.kubernetes.io/component: webhook
data:
  chaosfs-cockroachdb.yaml: |
    name: chaosfs-cockroachdb
    selector:
      labelSelectors:
        "app.kubernetes.io/component": "cockroachdb"
    initContainers:
    - name: inject-scripts
      image: pingcap/chaos-scripts:v0.8.0
      imagePullpolicy: Always
      command: ["sh", "-c", "/scripts/init.sh -d /cockroach/cockroach-data/data -f /cockroach/cockroach-data/fuse-data"]
    containers:
    - name: chaosfs
      image: pingcap/chaos-fs:v0.8.0
      imagePullpolicy: Always
      ports:
      - containerPort: 65534
      securityContext:
        privileged: true
      command:
        - /usr/local/bin/chaosfs
        - -addr=:65534
        - -pidfile=/tmp/fuse/pid
        - -original=/cockroach/cockroach-data/fuse-data
        - -mountpoint=/cockroach/cockroach-data/data
      volumeMounts:
        - name: datadir
          mountPath: /cockroach/cockroach-data
          mountPropagation: Bidirectional
    volumeMounts:
    - name: datadir
      mountPath: /cockroach/cockroach-data
      mountPropagation: HostToContainer
    - name: scripts
      mountPath: /tmp/scripts
    - name: fuse
      mountPath: /tmp/fuse
    volumes:
    - name: scripts
      emptyDir: {}
    - name: fuse
      emptyDir: {}
    postStart:
      cockroachdb:
        command:
          - /tmp/scripts/wait-fuse.sh
