---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaosfs-pd
  namespace: chaos-testing
  labels:
    app.kubernetes.io/component: webhook
data:
  chaosfs-pd: |
    name: chaosfs-pd
    selector:
      labelSelectors:
        "app.kubernetes.io/component": "pd"
    template: sidecar-template
    arguments:
      ContainerName: "pd"
      DataPath: "/var/lib/pd/data"
      MountPath: "/var/lib/pd"
      VolumeName: "pd"
