
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: jvmchaos.chaos-mesh.org
spec:
  group: chaos-mesh.org
  names:
    kind: JVMChaos
    listKind: JVMChaosList
    plural: jvmchaos
    singular: jvmchaos
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.action
      name: action
      type: string
    - jsonPath: .spec.duration
      name: duration
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: JVMChaos is the Schema for the jvmchaos API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: JVMChaosSpec defines the desired state of JVMChaos
            properties:
              action:
                description: 'Action defines the specific jvm chaos action. Supported
                  action: latency;return;exception;stress;gc;ruleData'
                enum:
                - latency
                - return
                - exception
                - stress
                - gc
                - ruleData
                type: string
              class:
                description: Java class
                type: string
              containerNames:
                description: ContainerNames indicates list of the name of affected
                  container. If not set, the first container will be injected
                items:
                  type: string
                type: array
              cpuCount:
                description: the CPU core number needs to use, only set it when action
                  is stress
                type: integer
              duration:
                description: Duration represents the duration of the chaos action
                type: string
              exception:
                description: the exception which needs to throw for action `exception`
                type: string
              latency:
                description: the latency duration for action 'latency', unit ms
                type: integer
              memType:
                description: the memory type needs to locate, only set it when action
                  is stress, the value can be 'stack' or 'heap'
                type: string
              method:
                description: the method in Java class
                type: string
              mode:
                description: 'Mode defines the mode to run chaos action. Supported
                  mode: one / all / fixed / fixed-percent / random-max-percent'
                enum:
                - one
                - all
                - fixed
                - fixed-percent
                - random-max-percent
                type: string
              name:
                description: byteman rule name, should be unique, and will generate
                  one if not set
                type: string
              pid:
                description: the pid of Java process which needs to attach
                type: integer
              port:
                description: the port of agent server, default 9277
                format: int32
                type: integer
              ruleData:
                description: the byteman rule's data for action 'ruleData'
                type: string
              selector:
                description: Selector is used to select pods that are used to inject
                  chaos action.
                properties:
                  annotationSelectors:
                    additionalProperties:
                      type: string
                    description: Map of string keys and values that can be used to
                      select objects. A selector based on annotations.
                    type: object
                  expressionSelectors:
                    description: a slice of label selector expressions that can be
                      used to select objects. A list of selectors based on set-based
                      label expressions.
                    items:
                      description: A label selector requirement is a selector that
                        contains values, a key, and an operator that relates the key
                        and values.
                      properties:
                        key:
                          description: key is the label key that the selector applies
                            to.
                          type: string
                        operator:
                          description: operator represents a key's relationship to
                            a set of values. Valid operators are In, NotIn, Exists
                            and DoesNotExist.
                          type: string
                        values:
                          description: values is an array of string values. If the
                            operator is In or NotIn, the values array must be non-empty.
                            If the operator is Exists or DoesNotExist, the values
                            array must be empty. This array is replaced during a strategic
                            merge patch.
                          items:
                            type: string
                          type: array
                      required:
                      - key
                      - operator
                      type: object
                    type: array
                  fieldSelectors:
                    additionalProperties:
                      type: string
                    description: Map of string keys and values that can be used to
                      select objects. A selector based on fields.
                    type: object
                  labelSelectors:
                    additionalProperties:
                      type: string
                    description: Map of string keys and values that can be used to
                      select objects. A selector based on labels.
                    type: object
                  namespaces:
                    description: Namespaces is a set of namespace to which objects
                      belong.
                    items:
                      type: string
                    type: array
                  nodeSelectors:
                    additionalProperties:
                      type: string
                    description: Map of string keys and values that can be used to
                      select nodes. Selector which must match a node's labels, and
                      objects must belong to these selected nodes.
                    type: object
                  nodes:
                    description: Nodes is a set of node name and objects must belong
                      to these nodes.
                    items:
                      type: string
                    type: array
                  podPhaseSelectors:
                    description: 'PodPhaseSelectors is a set of condition of a pod
                      at the current time. supported value: Pending / Running / Succeeded
                      / Failed / Unknown'
                    items:
                      type: string
                    type: array
                  pods:
                    additionalProperties:
                      items:
                        type: string
                      type: array
                    description: Pods is a map of string keys and a set values that
                      used to select pods. The key defines the namespace which pods
                      belong, and the each values is a set of pod names.
                    type: object
                type: object
              value:
                description: Value is required when the mode is set to `FixedMode`
                  / `FixedPercentMode` / `RandomMaxPercentMode`. If `FixedMode`, provide
                  an integer of pods to do chaos action. If `FixedPercentMode`, provide
                  a number from 0-100 to specify the percent of pods the server can
                  do chaos action. IF `RandomMaxPercentMode`,  provide a number from
                  0-100 to specify the max percent of pods to do chaos action
                type: string
            required:
            - action
            - mode
            - selector
            type: object
          status:
            description: JVMChaosStatus defines the observed state of JVMChaos
            properties:
              conditions:
                description: Conditions represents the current global condition of
                  the chaos
                items:
                  properties:
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              experiment:
                description: Experiment records the last experiment state.
                properties:
                  containerRecords:
                    description: Records are used to track the running status
                    items:
                      properties:
                        id:
                          type: string
                        phase:
                          type: string
                        selectorKey:
                          type: string
                      required:
                      - id
                      - phase
                      - selectorKey
                      type: object
                    type: array
                  desiredPhase:
                    enum:
                    - Run
                    - Stop
                    type: string
                type: object
            required:
            - experiment
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
