name: Unit Test And Code Coverage

# this workflow would work on all the prs
on:
  pull_request:
    paths:
      - makefile
      - go.*
      - "**.go"

jobs:
  unitTestAndCodeCoverage:
    name: "Unit Test And Code Coverage"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Unit Test
        run: |
          make test
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./cover.out
          verbose: true
          fail_ci_if_error: true
