name: Upload tagged install related files to CDN

on:
  push:
    tags:
      - v*

permissions: read-all

jobs:
  run:
    name: Upload
    runs-on: ubuntu-20.04
    steps:
      - name: "Must Triggered by Tag v<version>"
        run: |
          # GITHUB_REF_TYPE MUST equals to "tag"
          if [ "${GITHUB_REF_TYPE}" != "tag" ]; then
            echo "This workflow must be triggered by tag"
            echo "GITHUB_REF_TYPE: ${GITHUB_REF_TYPE}"
            echo "GITHUB_REF: ${GITHUB_REF}"
            exit 1
          fi

          # The tag MUST start with "v"
          GIT_TAG=${GITHUB_REF##*/}
          if [[ "${GIT_TAG}" == "v"* ]]; then
            exit 0
          fi

          echo "The tag must start with 'v'"
          echo "GITHUB_REF: ${GITHUB_REF}"
          exit 1
      - uses: actions/checkout@v4
        with:
          # Must use at least depth 2!
          fetch-depth: 2

      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version-file: "go.mod"
      - name: Configure awscli
        run: |
          pip3 install awscli
          printf "%s\n" ${{ secrets.AWS_ACCESS_KEY }} ${{ secrets.AWS_SECRET_KEY }} ${{ secrets.AWS_REGION }} "json" | aws configure

      - name: Build binary
        run: |
          make chaosctl
          make schedule-migration.tar.gz

      - name: Update install.sh with Certain Version
        run: |
          GIT_TAG=${GITHUB_REF##*/}
          VERSION=${GIT_TAG##chart-}
          sed install.sh -i -e "s/^VERSION=.*/VERSION=${VERSION}/"

      - name: Upload files
        run: |
          GIT_TAG=${GITHUB_REF##*/}
          aws s3 cp install.sh ${{ secrets.AWS_BUCKET_NAME }}/${GIT_TAG}/install.sh
          aws s3 cp manifests/crd.yaml ${{ secrets.AWS_BUCKET_NAME }}/${GIT_TAG}/crd.yaml
          aws s3 cp examples/web-show/deploy.sh ${{ secrets.AWS_BUCKET_NAME }}/${GIT_TAG}/web-show/deploy.sh
          aws s3 cp bin/chaosctl ${{ secrets.AWS_BUCKET_NAME }}/${GIT_TAG}/chaosctl
          aws s3 cp schedule-migration.tar.gz ${{ secrets.AWS_BUCKET_NAME }}/${GIT_TAG}/schedule-migration.tar.gz
